bump version
git-svn-id: file:///home/bacon/SVN/auto-admin/auto-admin-0.3.3@36 15dee832-e547-e211-8a70-0017315c2eee

diff --git a/Scripts/FreeBSD/auto-config-snd-driver b/Scripts/FreeBSD/auto-config-snd-driver
--- a/Scripts/FreeBSD/auto-config-snd-driver
+++ b/Scripts/FreeBSD/auto-config-snd-driver
@@ -9,7 +9,7 @@
 #       None
 #
 #   Returns:
-#       0 if a supported sound device is found, 1 otherwise.
+#       0 if a supported sound device is found, non-zero otherwise.
 #
 #   History:
 #   Date        Name        Modification
@@ -27,11 +27,36 @@ usage()
 #   Main
 ##########################################################################
 
-if [ $# != 1 ]; then
+if [ $# != 0 ]; then
     usage
 fi
 
-devnum=0
+if kldstat | grep -q snd_; then
+    cat << EOM
+
+=================================== Warning ==================================
+
+One or more sound drivers are already loaded.
+
+$0 works by detecting kernel messages
+for recognized devices after a new driver is loaded.
+
+In order to detect a device for which the driver is already loaded,
+you must remove all sound driver load entries from /boot/loader.conf
+and reboot.
+
+If you believe you have a device for which the driver is not loaded, (if
+you have installed a new sound card since the last scan, for instance),
+then it might make sense to scan now.
+
+EOM
+    printf "Scan for additional sound devices? (y/[n]) "
+    read continue
+    if [ 0$continue != 'y' ]; then
+	exit 0
+    fi
+fi
+
 for module in /boot/kernel/snd_*.ko; do
     driver=`basename ${module%%.ko}`
     if [ $driver != 'snd_driver' ]; then
@@ -41,7 +66,7 @@ for module in /boot/kernel/snd_*.ko; do
 		printf "Device found for $driver.  Updating loader.conf...\n"
 		auto-append-line "${driver}_load" "${driver}_load=\"YES\"" \
 		    /boot/loader.conf $0
-		devnum=$((devnum + 1))
+		exit 0
 	    else
 		kldunload $driver
 	    fi
@@ -49,9 +74,6 @@ for module in /boot/kernel/snd_*.ko; do
     fi
 done
 
-if [ $devnum -gt 0 ]; then
-    exit 0
-else
-    exit 1
-fi
+# No supported sound device found
+exit 1
 
