Fix auto-install-packages
git-svn-id: file:///home/bacon/SVN/auto-admin/auto-admin-0.3.4@57 15dee832-e547-e211-8a70-0017315c2eee

diff --git a/Scripts/FreeBSD/auto-ldap-client-setup b/Scripts/FreeBSD/auto-ldap-client-setup
--- a/Scripts/FreeBSD/auto-ldap-client-setup
+++ b/Scripts/FreeBSD/auto-ldap-client-setup
@@ -34,7 +34,7 @@ o=$3
 cacert=$4
 
 # Let this install as a dependency pkg_add -r openldap23-client
-auto-install-packages security/pam_ldap security/nss_ldap
+auto-install-packages security/pam_ldap net/nss_ldap
 
 # Install cert
 cp $cacert /usr/local/etc/openldap/cacert.crt
@@ -61,24 +61,22 @@ if ! fgrep -q login_attribute $ldap_conf; then
 fi
 
 # Tell PAM to use LDAP for ssh logins
-for file in sshd xdm; do
-    if ! fgrep -q pam_ldap.so /etc/pam.d/$file; then
-	awk ' { if ( $1 == "auth" && $3 == "pam_unix.so" )
-		{
-		    print "# Attempt and accept LDAP auth before unix auth"
-		    printf("auth\t\tsufficient\t/usr/local/lib/pam_ldap.so\tno_warn\n");
-		    print "# If LDAP auth fails, unix auth must succeed to grant access"
-		    print $0;
-		}
-		else
-		{
-		    print $0;
-		}
-	      }' /etc/pam.d/sshd > /etc/pam.d/temp
-	mv /etc/pam.d/sshd /etc/pam.d/sshd.orig
-	mv /etc/pam.d/temp /etc/pam.d/sshd
-    fi
-done
+if ! fgrep -q pam_ldap.so /etc/pam.d/sshd; then
+    awk ' { if ( $1 == "auth" && $3 == "pam_unix.so" )
+	    {
+		print "# Attempt and accept LDAP auth before unix auth"
+		printf("auth\t\tsufficient\t/usr/local/lib/pam_ldap.so\tno_warn\n");
+		print "# If LDAP auth fails, unix auth must succeed to grant access"
+		print $0;
+	    }
+	    else
+	    {
+		print $0;
+	    }
+	  }' /etc/pam.d/sshd > /etc/pam.d/temp
+    mv /etc/pam.d/sshd /etc/pam.d/sshd.orig
+    mv /etc/pam.d/temp /etc/pam.d/sshd
+fi
 
 printf "Updated /etc/pam.d/sshd.  Check/correct syntax if necessary.\n"
 #pause
