auto-dreckly-setup: Add bootstrapping with dreckly gcc

diff --git a/User-scripts/auto-dreckly-setup b/User-scripts/auto-dreckly-setup
--- a/User-scripts/auto-dreckly-setup
+++ b/User-scripts/auto-dreckly-setup
@@ -20,7 +20,7 @@ usage()
 {
     cat << EOM
 
-Usage: $0 [--help] [--extract-only] [boostrap-flags]
+Usage: $0 [--help] [--extract-only] [--bootstrap-gcc version] [boostrap-flags]
 
 The following bootstrap flags are generated by auto-dreckly-setup:
 
@@ -48,6 +48,10 @@ EOM
 
 if [ 0$1 = 0--extract-only ]; then
     EXTRACT_ONLY=yes
+    shift
+elif [ 0$1 = 0--bootstrap-gcc ]; then
+    GCC_VER=$2
+    shift
     shift
 elif [ 0$1 = 0--help ]; then
     usage
@@ -325,9 +329,15 @@ else
     dir_suffix=''
 fi
 
-prefix=$parent/pkg$dir_suffix
-dreckly_dir=$parent/dreckly$dir_suffix
-sys_dir=$parent/pkg$dir_suffix
+if [ -n "$GCC_VER" ]; then
+    prefix=$parent/pkg-gcc$GCC_VER$dir_suffix
+    dreckly_dir=$parent/dreckly-gcc$GCC_VER$dir_suffix
+    sys_dir=$parent/pkg-gcc$GCC_VER$dir_suffix
+else
+    prefix=$parent/pkg$dir_suffix
+    dreckly_dir=$parent/dreckly$dir_suffix
+    sys_dir=$parent/pkg$dir_suffix
+fi
 mk_conf=$sys_dir/etc/mk.conf
 
 cat << EOM
@@ -368,6 +378,9 @@ EOM
 # This may need alteration on some platforms, but it works on RHEL,
 # FreeBSD, NetBSD, and OS X.
 PATH=/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/usr/pkg/bin
+if [ -n "$COMPILER_PATH" ]; then
+    PATH=${COMPILER_PATH}:$PATH
+fi
 export PATH
 
 for cmd in git; do
@@ -471,8 +484,13 @@ You can add additional compiler flags here as well, all of which will be
 applied to every dreckly build.
 
 EOM
-printf "Build all compiled packages with -march=native? y/[n] "
-read march_native
+
+if [ -z "$GCC_VER" ]; then
+    printf "Build all compiled packages with -march=native? y/[n] "
+    read march_native
+else
+    march_native=n
+fi
 
 if which /usr/bin/fetch > /dev/null; then   # FreeBSD
     fetch_cmd=fetch
@@ -671,6 +689,26 @@ if [ 0$bootstrap = '0y' ]; then
     # Separate bootstrap settings
     printf "\n.ifdef BSD_PKG_MK       # Begin auto-dreckly-setup customizations\n\n" >> $mk_conf
 
+    if [ -n "$COMPILER_PATH" ]; then
+	for CC in cc gcc; do
+	    if [ -e $COMPILER_PATH/$CC ]; then
+		printf "CC?=\t\t\t$COMPILER_PATH/$CC\n" >> $mk_conf
+		break
+	    fi
+	done
+	for CXX in c++ g++; do
+	    if [ -e $COMPILER_PATH/$CXX ]; then
+		printf "CXX?=\t\t\t$COMPILER_PATH/$CXX\n" >> $mk_conf
+		break
+	    fi
+	done
+	for FC in gfortran; do
+	    if [ -e $COMPILER_PATH/$FC ]; then
+		printf "FC?=\t\t\t$COMPILER_PATH/$FC\n" >> $mk_conf
+		break
+	    fi
+	done
+    fi
     if [ -n "$OSX_TOLERATE_SDK_SKEW" ]; then
 	printf "OSX_TOLERATE_SDK_SKEW=\tyes\n" >> $mk_conf
     fi
@@ -720,11 +758,15 @@ if [ 0$bootstrap = '0y' ]; then
 	printf "PKGSRC_FORTRAN=\t\tgfortran\n" >> $mk_conf
     fi
     
-    printf "Will you be using this installation for package development? y/[n] "
-    read developer
-    if [ 0$developer = 0y ]; then
-	if ! fgrep PKG_DEVELOPER $mk_conf; then
-	    printf "PKG_DEVELOPER=\t\tyes\n" >> $mk_conf
+    if [ -n "$GCC_VER" ]; then
+	developer=n
+    else
+	printf "Will you be using this installation for package development? y/[n] "
+	read developer
+	if [ 0$developer = 0y ]; then
+	    if ! fgrep PKG_DEVELOPER $mk_conf; then
+		printf "PKG_DEVELOPER=\t\tyes\n" >> $mk_conf
+	    fi
 	fi
     fi
     
@@ -764,8 +806,13 @@ type.  Do this only if you are certain that your organization has no
 restrictions on the allowable types of licenses.
 
 EOM
-    printf "Accept all software licenses? [y]/n "
-    read skip_license_check
+    if [ -z "$GCC_VER" ]; then
+	printf "Accept all software licenses? [y]/n "
+	read skip_license_check
+    else
+	skip_license_check=y
+    fi
+    
     if [ 0$skip_license_check != 0n ]; then
 	printf "SKIP_LICENSE_CHECK=\tyes\n" >> $mk_conf
     else
@@ -856,6 +903,9 @@ If you would like to use a dreckly GCC compiler to build most packages
 number below.  The major version is the number following "gcc" in the
 list of packages below.
 
+Determining the best compiler for your needs is a matter of trial and
+error, though in general, the 2nd newest compiler is usually a good bet.
+
 Available gcc packages:
 
 EOM
@@ -876,7 +926,7 @@ EOM
     
     # Keep this in sync with pbulk-setup for installations that use both
     # binary packages and build from source.
-    if [ ! -z $base_gcc ]; then
+    if [ -n "$base_gcc" ]; then
 	cat << EOM >> $mk_conf
 
 .ifdef BSD_PKG_MK   # dreckly
@@ -985,15 +1035,21 @@ ${prefix}/sbin/pkg_admin \
 
 # Generate startup script segments
 
+# Prepend COMPILER_PATH to user's PATH if not empty
+if [ -n "$COMPILER_PATH" ]; then
+    COMPILER_PATH_COLON="${COMPILER_PATH}:"
+fi
+
 cat << EOM > ${sys_dir}/etc/dreckly.sh
 # Generated by auto-dreckly-setup
+# Set env for this dreckly tree if not already set
 if ! echo \$PATH | fgrep -q "${prefix}/bin:"; then
     DRECKLY=$prefix
     export DRECKLY
     
     # Scrub PATH and LD_LIBRARY_PATH before adding dreckly to prevent leakage
     # RHEL 7 /bin/gcc fails with cannot find cc1, so put /usr/bin first
-    PATH=/usr/bin:/usr/sbin:/bin:/sbin
+    PATH=$PATH
     unset CC CFLAGS CXX CXXFLAGS CPP CPPFLAGS CPATH \
 	C_INCLUDE_PATH CPLUS_INCLUDE_PATH OBJC_INCLUDE_PATH \
 	FC FFLAGS GFLAGS LD LDFLAGS LD_LIBRARY_PATH LDLIBS
@@ -1019,6 +1075,7 @@ EOM
 # Keep this in sync with the script above.  Just remove the scrub lines.
 cat << EOM > ${sys_dir}/etc/dreckly-non-exclusive.sh
 # Generated by auto-dreckly-setup
+# Set env for this dreckly tree if not already set
 if ! echo \$PATH | fgrep -q "${prefix}/bin:"; then
     DRECKLY=$prefix
     export DRECKLY
@@ -1032,7 +1089,7 @@ if ! echo \$PATH | fgrep -q "${prefix}/bin:"; then
 	fi
     fi
     
-    PATH=\$DRECKLY/bin:\$DRECKLY/sbin:\$PATH
+    PATH=${COMPILER_PATH_COLON}\$DRECKLY/bin:\$DRECKLY/sbin:\$PATH
     export PATH
     DRECKLY_INCLUDE=\$DRECKLY/include
     export DRECKLY_INCLUDE
@@ -1043,13 +1100,14 @@ EOM
 
 cat << EOM > ${sys_dir}/etc/dreckly.csh
 # Generated by auto-dreckly-setup
+# Set env for this dreckly tree if not already set
 echo \$PATH | fgrep -q "${prefix}/bin:"
 if ( \$status != 0 ) then
     setenv DRECKLY           $prefix
     
     # Scrub PATH and LD_LIBRARY_PATH before adding dreckly to prevent leakage
     # RHEL 7 /bin/gcc fails with cannot find cc1, so put /usr/bin first
-    setenv PATH             /usr/bin:/usr/sbin:/bin:/sbin
+    setenv PATH $PATH
     unsetenv CC CFLAGS CXX CXXFLAGS CPP CPPFLAGS CPATH \
 	C_INCLUDE_PATH CPLUS_INCLUDE_PATH OBJC_INCLUDE_PATH \
 	FC FFLAGS GFLAGS LD LDFLAGS LD_LIBRARY_PATH LDLIBS
@@ -1072,6 +1130,7 @@ EOM
 # Keep this in sync with the script above.  Just remove the scrub lines.
 cat << EOM > ${sys_dir}/etc/dreckly-non-exclusive.csh
 # Generated by auto-dreckly-setup
+# Set env for this dreckly tree if not already set
 echo \$PATH | fgrep -q "${prefix}/bin:"
 if ( \$status != 0 ) then
     setenv DRECKLY           $prefix
@@ -1085,7 +1144,7 @@ if ( \$status != 0 ) then
 	endif
     endif
     
-    setenv PATH             \$DRECKLY/bin:\$DRECKLY/sbin:\$PATH
+    setenv PATH              ${COMPILER_PATH_COLON}\$DRECKLY/bin:\$DRECKLY/sbin:\$PATH
     setenv DRECKLY_INCLUDE   \$DRECKLY/include
     setenv DRECKLY_LIB       \$DRECKLY/lib
 endif
@@ -1187,14 +1246,14 @@ if ! echo \$PATH | fgrep -q "${prefix}/gcc$gcc/bin:"; then
     dreckly=$prefix
     export dreckly
     
-    PATH=\$DRECKLY/gcc$gcc/bin:\$PATH
+    PATH=${COMPILER_PATH_COLON}\$DRECKLY/gcc$gcc/bin:\$PATH
     export PATH
     # dreckly gcc man pages broken
     # MANPATH=\$DRECKLY/gcc$gcc/man:\$DRECKLY/man:\$DRECKLY/share/man:/usr/share/man
     # export MANPATH
-    DRECKLY_GCC_INCLUDE=\$DRECKLY/gcc$gcc/include
+    DRECKLY_INCLUDE=\$DRECKLY/gcc$gcc/include
     export DRECKLY_INCLUDE
-    DRECKLY_GCC_LIB=\$DRECKLY/gcc$gcc/lib
+    DRECKLY_LIB=\$DRECKLY/gcc$gcc/lib
     export DRECKLY_LIB
 fi
 EOM
@@ -1207,9 +1266,9 @@ echo \$PATH | fgrep -q "${prefix}/gcc$gcc/bin:"
 if ( \$status != 0 ) then
     setenv DRECKLY   $prefix
     
-    setenv PATH                 \$DRECKLY/gcc$gcc/bin:\$PATH
+    setenv PATH                  ${COMPILER_PATH_COLON}\$DRECKLY/gcc$gcc/bin:\$PATH
     # dreckly gcc man pages broken
-    # setenv MANPATH            \$DRECKLY/gcc$gcc/man:\$DRECKLY/man:\$DRECKLY/share/man:/usr/share/man
+    # setenv MANPATH             \$DRECKLY/gcc$gcc/man:\$DRECKLY/man:\$DRECKLY/share/man:/usr/share/man
     setenv DRECKLY_GCC_INCLUDE   \$DRECKLY/gcc$gcc/include
     setenv DRECKLY_GCC_LIB       \$DRECKLY/gcc$gcc/lib
 endif
@@ -1241,7 +1300,7 @@ EOM
     fi    
 done    # while [ -e $dreckly_dir/lang/gcc$gcc ]
 
-if [ ! -z $base_gcc ]; then
+if [ -n "$base_gcc" ]; then
     ln -f ${sys_dir}/etc/$base_gcc.sh ${sys_dir}/etc/gcc-base.sh
     ln -f ${sys_dir}/etc/$base_gcc.csh ${sys_dir}/etc/gcc-base.csh
     ln -f ${sys_dir}/etc/modulefiles/dreckly/$base_gcc \
@@ -1311,8 +1370,13 @@ packages that don't yet exist in the official dreckly collection.
 You can also contribute your own packages and bug fixes.
 
 EOM
-printf "Install pkgsrc-wip? y/[n] "
-read install_wip
+if [ -z "$GCC_VER" ]; then
+    printf "Install pkgsrc-wip? y/[n] "
+    read install_wip
+else
+    install_wip=n
+fi
+
 if [ 0$install_wip = 0y ]; then
     cd $dreckly_dir
     
@@ -1357,7 +1421,8 @@ else
     os=$(uname)-$(uname -r)
 fi
 
-cat << EOM
+if [ -z "GCC_VER" ]; then
+    cat << EOM
 
 ============================================================================
 
@@ -1378,59 +1443,59 @@ if this is incorrect.
 
 EOM
 
-cat << EOM
+    cat << EOM
 
 Enter a binary package server name (include http:// or https://), or
 just press enter if you won't be using binary packages.
 
 EOM
-read package_server
-if [ 0$package_server != 0 ]; then
-    pkg_path=${pkg_path}$package_server/dreckly/packages$prefix/$os/All\;
-    pkgin_path="${pkgin_path}$package_server/dreckly/packages$prefix/$os/All\n"
-fi
-
-if [ 0$pkg_path != 0 ]; then
-    printf "PKG_PATH=$pkg_path\n" >> $sys_dir/etc/pkg_install.conf
-
-    # Rebuild pkg_install with SSL support
-    cd $dreckly_dir/pkgtools/pkg_install
-    bmake clean
-    bmake clean-depends
-    bmake replace ALLOW_VULNERABLE_PACKAGES=yes
+    read package_server
+    if [ 0$package_server != 0 ]; then
+	pkg_path=${pkg_path}$package_server/dreckly/packages$prefix/$os/All\;
+	pkgin_path="${pkgin_path}$package_server/dreckly/packages$prefix/$os/All\n"
+    fi
     
-    # Install numerous deps to save time
-    pkg_add pkgin
-    # unset PKG_PATH
+    if [ 0$pkg_path != 0 ]; then
+	printf "PKG_PATH=$pkg_path\n" >> $sys_dir/etc/pkg_install.conf
     
-    # Reinstall libfetch and pkgin from source to enable SSL.
-    # mk.conf should contain "PKG_OPTIONS.libfetch=inet6 openssl" by now
-    pkg_delete -f libfetch pkgin
-    save_cwd=`pwd`
-    cd $dreckly_dir/pkgtools/pkgin
-    bmake clean
-    bmake clean-depends
-    bmake install
-    if [ $? = 0 ]; then
-	printf "${pkgin_path}" >> $sys_dir/etc/pkgin/repositories.conf
-	pkgin update
-	cat << EOM
+	# Rebuild pkg_install with SSL support
+	cd $dreckly_dir/pkgtools/pkg_install
+	bmake clean
+	bmake clean-depends
+	bmake replace ALLOW_VULNERABLE_PACKAGES=yes
+	
+	# Install numerous deps to save time
+	pkg_add pkgin
+	# unset PKG_PATH
+	
+	# Reinstall libfetch and pkgin from source to enable SSL.
+	# mk.conf should contain "PKG_OPTIONS.libfetch=inet6 openssl" by now
+	pkg_delete -f libfetch pkgin
+	save_cwd=`pwd`
+	cd $dreckly_dir/pkgtools/pkgin
+	bmake clean
+	bmake clean-depends
+	bmake install
+	if [ $? = 0 ]; then
+	    printf "${pkgin_path}" >> $sys_dir/etc/pkgin/repositories.conf
+	    pkgin update
+	    cat << EOM
 
 Pkgin initialized successfully.  You can use pkgin to install and remove
 binary packages, list available packages, etc.  Run "man pkgin" for details.
 
 EOM
-	if [ ! -z $base_gcc ]; then
-	    pkgin -y install $base_gcc
+	    if [ -n "$base_gcc" ]; then
+		pkgin -y install $base_gcc
+	    fi
+	else
+	    printf "Failed to install pkgin.\nCheck $sys_dir/etc/pkg_install.conf.\n"
 	fi
-    else
-	printf "Failed to install pkgin.\nCheck $sys_dir/etc/pkg_install.conf.\n"
+	cd $save_cwd
+	pause
     fi
-    cd $save_cwd
-    pause
-fi
 
-cat << EOM
+    cat << EOM
 ==============================================================================
 Unlike some other package managers, dreckly does not install any specific
 certificates automatically.  Instead, it is left to the user to decide which
@@ -1450,23 +1515,23 @@ They can be installed at any time, but doing it now might prevent problems
 for all users of this system.
 
 EOM
-printf "Install Mozilla certs now? y/[n] "
-read install_certs
-if [ 0$install_certs = 0y ]; then
-    save_cwd=$(pwd)
-    cd $dreckly_dir/security/mozilla-rootcerts && bmake clean install
-    # mozilla-rootcerts-openssl won't install on NetBSD
-    if [ $(uname) != NetBSD ] || [ $(id -un) = root ]; then
-	cd $dreckly_dir/security/mozilla-rootcerts-openssl
+    printf "Install Mozilla certs now? y/[n] "
+    read install_certs
+    if [ 0$install_certs = 0y ]; then
+	save_cwd=$(pwd)
+	cd $dreckly_dir/security/mozilla-rootcerts && bmake clean install
+	# mozilla-rootcerts-openssl won't install on NetBSD
+	if [ $(uname) != NetBSD ] || [ $(id -un) = root ]; then
+	    cd $dreckly_dir/security/mozilla-rootcerts-openssl
+	fi
+	if ! bmake clean install; then
+	    printf "Warning: mozilla-rootcerts-openssl failed.\n"
+	    pause
+	fi
+	cd $save_cwd
     fi
-    if ! bmake clean install; then
-	printf "Warning: mozilla-rootcerts-openssl failed.\n"
-	pause
-    fi
-    cd $save_cwd
-fi
 
-cat << EOM
+    cat << EOM
 
 ********************************** WARNING **********************************
 
@@ -1486,9 +1551,9 @@ generated by auto-dreckly-setup, performs a simple check to ensure that you
 are using the correct bmake binary for the tree in which you are building.
 
 EOM
-pause
-
-cat << EOM
+    pause
+    
+    cat << EOM
 ============================================================================
 Users running sh-compatible shells can use the following to configure the
 environment for this installation:
@@ -1505,9 +1570,9 @@ of one of the commands above:
     module load ${sys_dir}/etc/modulefiles/dreckly/${dist_suffix#-}
 ============================================================================
 EOM
-pause
-
-cat << EOM
+    pause
+    
+    cat << EOM
 ============================================================================
 To install a package, type:
 
@@ -1519,9 +1584,9 @@ Ex.
     safe-bmake install
 ============================================================================
 EOM
-pause
-
-cat << EOM
+    pause
+    
+    cat << EOM
 ============================================================================
 After setting the environment using one of the commands above, to compile
 and link programs using libraries installed by dreckly, use:
@@ -1536,15 +1601,15 @@ Ex. Assuming your Makefile uses CFLAGS for compiling and LFLAGS for link:
 For more information, go to https://www.netbsd.org/docs/pkgsrc/
 ============================================================================
 EOM
-pause
-
-cat << EOM
+    pause
+    
+    cat << EOM
 ============================================================================
 You can keep your dreckly tree up-to-date by periodically running the
 following commands:
 
     cd $dreckly_dir
-    cvs -q update -dP
+    git pull
 
 The devel/scmcvs package provides a cvs command in case your system does
 not already have one.
@@ -1562,15 +1627,16 @@ use
 ============================================================================
 EOM
 
-# Install dreckly guide onto desktop
-if [ -e $HOME/Desktop ] && [ ! -e $HOME/Desktop/Guides/dreckly.pdf ]; then
-    PATH=$PATH:/usr/local/bin   # Find curl on BSD
-    export PATH
-    mkdir -p $HOME/Desktop/Guides
-    cd $HOME/Desktop/Guides
-    printf "Fetching manual...\n"
-    $fetch_cmd https://www.netbsd.org/docs/pkgsrc/pkgsrc.pdf
-    printf "A copy of the dreckly guide has been placed on your desktop.\n"
+    # Install dreckly guide onto desktop
+    if [ -e $HOME/Desktop ] && [ ! -e $HOME/Desktop/Guides/dreckly.pdf ]; then
+	PATH=$PATH:/usr/local/bin   # Find curl on BSD
+	export PATH
+	mkdir -p $HOME/Desktop/Guides
+	cd $HOME/Desktop/Guides
+	printf "Fetching manual...\n"
+	$fetch_cmd https://www.netbsd.org/docs/pkgsrc/pkgsrc.pdf
+	printf "A copy of the dreckly guide has been placed on your desktop.\n"
+    fi
 fi
 
 touch $parent/pkg$dir_suffix/done
@@ -1578,9 +1644,10 @@ touch $parent/pkg$dir_suffix/done
 # Generate bootstrap kit
 cd $start_dir
 bootstrap_archive=`echo dreckly-$os-$compiler$prefix.tgz | tr / -`
-printf "Creating bootstrap kit: $bootstrap_archive...\n"
-$tar zcf $bootstrap_archive $prefix $dreckly_dir $sys_dir || true
-cat << EOM
+if [ ! -e $bootstrap_archive ]; then
+    printf "Creating bootstrap kit: $bootstrap_archive...\n"
+    $tar zcf $bootstrap_archive $prefix $dreckly_dir $sys_dir || true
+    cat << EOM
 
 Bootstrap image saved to $bootstrap_archive.
 
@@ -1588,13 +1655,26 @@ You can unpack this file to / on other identical $(uname) systems in order to
 quickly replicate this installation.
 
 EOM
-pause
+    pause
+else
+    printf "$bootstrap_archive already exists.\n"
+fi
 
-(cd $dreckly_dir/sysutils/auto-admin && bmake clean install)
-auto-software-manager
-
-cat << EOM
+if [ -n "$GCC_VER" ]; then
+    # Now bootstrap again using the dreckly GCC tree
+    if [ ! -e $prefix/gcc$GCC_VER/bin ]; then
+	(cd $dreckly_dir/lang/gcc$GCC_VER && time bmake clean install)
+    fi
+    COMPILER_PATH=$prefix/gcc$GCC_VER/bin
+    export COMPILER_PATH
+    $0
+else
+    (cd $dreckly_dir/sysutils/auto-admin && bmake clean install)
+    auto-software-manager
+    cat << EOM
 
 Run auto-software-manager for a menu interface to dreckly.
 
 EOM
+fi
+
