auto-update-system: Fix reboot checks

diff --git a/Sys-scripts/auto-update-system b/Sys-scripts/auto-update-system
--- a/Sys-scripts/auto-update-system
+++ b/Sys-scripts/auto-update-system
@@ -684,15 +684,15 @@ rebooting if a reboot is needed.
 
 EOM
 		fi
-		
-		# Reboot only if kernel or modules updated
-		if [ 0$reboot_requested = 0y ] && grep -q '^/boot' $tmpfile; then
-		    printf "Kernel componented updated.  System will reboot.\n"
-		    reboot=y
-		else
-		    printf "No kernel componented updated.  No reboot necessary.\n"
-		    reboot=n
-		fi
+	    fi
+	    
+	    # Reboot only if kernel or modules updated
+	    if [ 0$reboot_requested = 0y ] && grep -q '^/boot' $tmpfile; then
+		printf "Kernel componented updated.  System will reboot.\n"
+		reboot=y
+	    else
+		printf "No kernel componented updated.  No reboot necessary.\n"
+		reboot=n
 	    fi
 	    rm $tmpfile
     
@@ -871,11 +871,6 @@ interactive)
     ;;
 esac
 
-# Restart services in case daemons were updated
-# FIXME: Not ideal to tolerate failures in service restarts, but there
-# are too many things that can result in a non-zero exit status
-auto-restart-services || true
-
 if [ 0$reboot = 0y ]; then
     if [ $mode = interactive ]; then
 	printf "Minutes to reboot? [2] "
@@ -890,6 +885,11 @@ if [ 0$reboot = 0y ]; then
     sync    # Attempt to prevent Linux kernel update failures
     shutdown -r +$minutes
 else
+    # Restart services in case daemons were updated
+    # FIXME: Not ideal to tolerate failures in service restarts, but there
+    # are too many things that can result in a non-zero exit status
+    auto-restart-services || true
+
     cat << EOM
 
 Be sure to reboot if you've updated the kernel, or restart any services
