auto-update-system: stash bsd.local.mk only of changes detected

diff --git a/Sys-scripts/auto-update-system b/Sys-scripts/auto-update-system
--- a/Sys-scripts/auto-update-system
+++ b/Sys-scripts/auto-update-system
@@ -465,14 +465,22 @@ EOM
 	    if [ -e $PORTSDIR/.git ]; then
 		save_cwd=$(pwd)
 		cd $PORTSDIR
-		printf "Stashing bsd.local.mk...\n"
-		git stash push Mk/bsd.local.mk || true
-
+		stash_file=Mk/bsd.local.mk
+		if ! git diff --quiet $stash_file; then
+		    stash=1
+		fi
+		if [ 0$stash = 01 ]; then
+		    printf "Stashing bsd.local.mk...\n"
+		    git stash push Mk/bsd.local.mk || true
+		fi
+		
 		printf "Pulling...\n"
 		git pull
 
-		printf "Unstashing...\n"
-		git stash pop || true   # Returns non-zero if nothing stashed
+		if [ 0$stash = 01 ]; then
+		    printf "Unstashing...\n"
+		    git stash pop || true   # Returns non-zero if nothing stashed
+		fi
 		cd $save_cwd
 	    else
 		cat << EOM
